{
 "title": "Chaos Mesh Experiments Dashboard",
 "tags": [
  "chaos-mesh",
  "kubernetes",
  "devops"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage per Pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "core" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\",container!=\"\",pod!=\"\"}[2m])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {}
   ]
  },
  {
   "title": "Memory Usage per Pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"$namespace\",container!=\"\",pod!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Throughput (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{namespace=\"$namespace\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{namespace=\"$namespace\"}[30s]))\n  /\nsum(rate(http_request_duration_seconds_count{namespace=\"$namespace\"}[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{namespace=\"$namespace\"}[30s])) by (le,pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Latency (95th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{namespace=\"$namespace\"}[30s])) by (le,pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Network Latency (50th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket{namespace=\"$namespace\"}[30s])) by (le,pod))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (deployment) ( kube_deployment_status_replicas_available{namespace=\"test\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Error Rate (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"$namespace\",status=~\"5..\"}[30s])) by (pod) or vector(0)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error Rate 4xx",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{namespace=\"$namespace\",status=~\"4..\"}[30s])) by (pod) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_bucket{namespace=\"test\"}[1m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Pod Restart Count",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "count(kube_pod_container_status_restarts_total{namespace=\"$namespace\",container=\"podinfo\"}) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Down Duration",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 23 },
   "targets": [
    {
     "expr": "kube_pod_status_phase{namespace=\"$namespace\",phase!=\"Running\"}",
     "legendFormat": "{{pod}} ({{phase}})"
    }
   ]
  }
 ]
}